manifest:

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: main
      path: zephyr
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis
          - cmsis_6

    - name: openocd
      url: https://github.com/spacecubics/openocd.git
      revision: release-scobc-a1-openocd
      path: modules/tools/openocd
