manifest:

  projects:
    - name: zephyr
      url: https://github.com/spacecubics/zephyr.git
      revision: support-west-flash-to-nor
      path: zephyr
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - littlefs

    - name: openocd
      url: https://github.com/spacecubics/openocd.git
      revision: release-scobc-a1-openocd
      path: modules/tools/openocd
