name: Simple Build Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 21 * * *' # Run it every day at 9pm UTC

jobs:
  simple-build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - zephyr/samples/hello_world
          - zephyr/samples/basic/blinky
          - scobc-a1-sample/samples/hello_world
          - scobc-a1-sample/samples/blinky
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
        os:
          - ubuntu-24.04
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python version
        run: |
          python3 --version

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: scobc-a1-sample

      - name: Setup Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: scobc-a1-sample
          toolchains: arm-zephyr-eabi

      - name: Build
        run: |
          west build -b scobc_a1 --shield scobc_a1_dev ${{ matrix.target }}

  status-check:
    runs-on: ubuntu-latest
    needs: simple-build
    steps:
      - name: All test passed
        run: echo Ready to merge
